FROM python:3.10

WORKDIR /app

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

ENV PORT 7860

CMD streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
